package eu.fp.concesionario;

import java.awt.Component;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.*;

/**
 *
 * @author Karina
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboar
     */
    public Dashboard() {
        initComponents();
        addActionToMenuLabels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VentanaCompleta = new javax.swing.JPanel();
        PanelMenu = new javax.swing.JPanel();
        MenuHeader = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        icono = new javax.swing.JLabel();
        MenuVENTAS = new javax.swing.JPanel();
        VentasInicio = new javax.swing.JLabel();
        VentasFacturas = new javax.swing.JLabel();
        VentasMotores = new javax.swing.JLabel();
        VentasVehiculos = new javax.swing.JLabel();
        VentasClientes = new javax.swing.JLabel();
        VentasADMIN = new javax.swing.JLabel();
        VentasTALLER = new javax.swing.JLabel();
        MenuTALLER = new javax.swing.JPanel();
        TallerInicio = new javax.swing.JLabel();
        TallerFacturas = new javax.swing.JLabel();
        TallerReservas = new javax.swing.JLabel();
        TallerClientes = new javax.swing.JLabel();
        TallerADMIN = new javax.swing.JLabel();
        TallerVENTAS = new javax.swing.JLabel();
        MenuADMIN = new javax.swing.JPanel();
        AdminInicio = new javax.swing.JLabel();
        AdminFacturas = new javax.swing.JLabel();
        AdminEmpleados = new javax.swing.JLabel();
        AdminNominas = new javax.swing.JLabel();
        AdminVentas = new javax.swing.JLabel();
        AdminTaller = new javax.swing.JLabel();
        MenuCLIENTE = new javax.swing.JPanel();
        ClienteInicio = new javax.swing.JLabel();
        ClienteAreaPersonal = new javax.swing.JLabel();
        ClienteReservas = new javax.swing.JLabel();
        ClienteFacturas = new javax.swing.JLabel();
        PanelBoard = new javax.swing.JPanel();
        Board_Facturas = new javax.swing.JPanel();
        Title_Facturas = new javax.swing.JLabel();
        Facturas_Scroll = new javax.swing.JScrollPane();
        Facturas_Tabla = new javax.swing.JTable();
        Facturas_Buscar = new javax.swing.JButton();
        Facturas_Anadir = new javax.swing.JButton();
        Facturas_Modificar = new javax.swing.JButton();
        Facturas_Eliminar = new javax.swing.JButton();
        Board_Motores = new javax.swing.JPanel();
        LabelTitle_Motores = new javax.swing.JLabel();
        Board_Vehiculos = new javax.swing.JPanel();
        LabelTitle_Vehiculos = new javax.swing.JLabel();
        Board_Inicio = new javax.swing.JPanel();
        Label_SesionNIF = new javax.swing.JLabel();
        LabelTitle_Inicio = new javax.swing.JLabel();
        Board_Reservas = new javax.swing.JPanel();
        LabelTitle_Reservas = new javax.swing.JLabel();
        Board_Empleados = new javax.swing.JPanel();
        LabelTitle_Empleados = new javax.swing.JLabel();
        Board_Nominas = new javax.swing.JPanel();
        LabelTitle_Nominas = new javax.swing.JLabel();
        Board_AreaCliente = new javax.swing.JPanel();
        LabelTitle_AreaCliente = new javax.swing.JLabel();
        Board_Clientes = new javax.swing.JPanel();
        Title_Clientes = new javax.swing.JLabel();
        Clientes_Scroll = new javax.swing.JScrollPane();
        Cliente_Tabla = new javax.swing.JTable();
        Clientes_Buscar = new javax.swing.JButton();
        Clientes_Anadir = new javax.swing.JButton();
        Clientes_Modificar = new javax.swing.JButton();
        Clientes_Eliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard Concesionario");

        VentanaCompleta.setBackground(new java.awt.Color(255, 255, 255));
        VentanaCompleta.setPreferredSize(new java.awt.Dimension(1280, 720));

        PanelMenu.setBackground(new java.awt.Color(51, 51, 51));

        MenuHeader.setBackground(new java.awt.Color(51, 51, 51));
        MenuHeader.setName("Header"); // NOI18N

        Title.setFont(new java.awt.Font("SansSerif", 3, 24)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 0));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Title.setText("Concesionario");
        Title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        icono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icono.setText("icono");
        icono.setIconTextGap(0);

        javax.swing.GroupLayout MenuHeaderLayout = new javax.swing.GroupLayout(MenuHeader);
        MenuHeader.setLayout(MenuHeaderLayout);
        MenuHeaderLayout.setHorizontalGroup(
            MenuHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuHeaderLayout.createSequentialGroup()
                .addComponent(icono, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuHeaderLayout.setVerticalGroup(
            MenuHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuHeaderLayout.createSequentialGroup()
                .addComponent(icono, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        MenuVENTAS.setBackground(new java.awt.Color(51, 51, 51));

        VentasInicio.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        VentasInicio.setForeground(new java.awt.Color(255, 255, 255));
        VentasInicio.setText("Inicio");
        VentasInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VentasInicio.setName("inicio"); // NOI18N

        VentasFacturas.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        VentasFacturas.setForeground(new java.awt.Color(255, 255, 255));
        VentasFacturas.setText("Facturas");
        VentasFacturas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VentasFacturas.setName("facturas"); // NOI18N

        VentasMotores.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        VentasMotores.setForeground(new java.awt.Color(255, 255, 255));
        VentasMotores.setText("Motores");
        VentasMotores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VentasMotores.setName("motores"); // NOI18N

        VentasVehiculos.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        VentasVehiculos.setForeground(new java.awt.Color(255, 255, 255));
        VentasVehiculos.setText("Vehiculos");
        VentasVehiculos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VentasVehiculos.setName("vehiculos"); // NOI18N

        VentasClientes.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        VentasClientes.setForeground(new java.awt.Color(255, 255, 255));
        VentasClientes.setText("Clientes");
        VentasClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VentasClientes.setName("clientes"); // NOI18N

        VentasADMIN.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        VentasADMIN.setForeground(new java.awt.Color(255, 255, 255));
        VentasADMIN.setText("Regresar a ADMINISTRACIÓN");
        VentasADMIN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VentasADMIN.setName("admin"); // NOI18N

        VentasTALLER.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        VentasTALLER.setForeground(new java.awt.Color(255, 255, 255));
        VentasTALLER.setText("Acceder a TALLER");
        VentasTALLER.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VentasTALLER.setName("taller"); // NOI18N

        javax.swing.GroupLayout MenuVENTASLayout = new javax.swing.GroupLayout(MenuVENTAS);
        MenuVENTAS.setLayout(MenuVENTASLayout);
        MenuVENTASLayout.setHorizontalGroup(
            MenuVENTASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuVENTASLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuVENTASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VentasMotores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VentasInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VentasFacturas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VentasVehiculos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                    .addComponent(VentasClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VentasADMIN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VentasTALLER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        MenuVENTASLayout.setVerticalGroup(
            MenuVENTASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuVENTASLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VentasInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VentasFacturas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VentasVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VentasMotores, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VentasClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 251, Short.MAX_VALUE)
                .addComponent(VentasTALLER, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VentasADMIN, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        MenuTALLER.setBackground(new java.awt.Color(51, 51, 51));

        TallerInicio.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TallerInicio.setForeground(new java.awt.Color(255, 255, 255));
        TallerInicio.setText("Inicio");
        TallerInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TallerInicio.setName("inicio"); // NOI18N

        TallerFacturas.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TallerFacturas.setForeground(new java.awt.Color(255, 255, 255));
        TallerFacturas.setText("Facturas");
        TallerFacturas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TallerFacturas.setName("facturas"); // NOI18N

        TallerReservas.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TallerReservas.setForeground(new java.awt.Color(255, 255, 255));
        TallerReservas.setText("Reservas");
        TallerReservas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TallerReservas.setName("reservas"); // NOI18N

        TallerClientes.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TallerClientes.setForeground(new java.awt.Color(255, 255, 255));
        TallerClientes.setText("Clientes");
        TallerClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TallerClientes.setName("clientes"); // NOI18N

        TallerADMIN.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TallerADMIN.setForeground(new java.awt.Color(255, 255, 255));
        TallerADMIN.setText("Regresar a ADMINISTRACIÓN");
        TallerADMIN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TallerADMIN.setName("admin"); // NOI18N

        TallerVENTAS.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TallerVENTAS.setForeground(new java.awt.Color(255, 255, 255));
        TallerVENTAS.setText("Acceder a VENTAS");
        TallerVENTAS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TallerVENTAS.setName("ventas"); // NOI18N

        javax.swing.GroupLayout MenuTALLERLayout = new javax.swing.GroupLayout(MenuTALLER);
        MenuTALLER.setLayout(MenuTALLERLayout);
        MenuTALLERLayout.setHorizontalGroup(
            MenuTALLERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuTALLERLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuTALLERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TallerInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TallerFacturas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TallerReservas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                    .addComponent(TallerClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TallerADMIN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TallerVENTAS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        MenuTALLERLayout.setVerticalGroup(
            MenuTALLERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuTALLERLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TallerInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TallerFacturas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TallerReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TallerClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 307, Short.MAX_VALUE)
                .addComponent(TallerVENTAS, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TallerADMIN, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        MenuADMIN.setBackground(new java.awt.Color(51, 51, 51));

        AdminInicio.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        AdminInicio.setForeground(new java.awt.Color(255, 255, 255));
        AdminInicio.setText("Inicio");
        AdminInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AdminInicio.setName("inicio"); // NOI18N

        AdminFacturas.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        AdminFacturas.setForeground(new java.awt.Color(255, 255, 255));
        AdminFacturas.setText("Facturas");
        AdminFacturas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AdminFacturas.setName("facturas"); // NOI18N

        AdminEmpleados.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        AdminEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        AdminEmpleados.setText("Empleados");
        AdminEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AdminEmpleados.setName("empleados"); // NOI18N

        AdminNominas.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        AdminNominas.setForeground(new java.awt.Color(255, 255, 255));
        AdminNominas.setText("Nominas");
        AdminNominas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AdminNominas.setName("nominas"); // NOI18N

        AdminVentas.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        AdminVentas.setForeground(new java.awt.Color(255, 255, 255));
        AdminVentas.setText("Acceder a VENTAS");
        AdminVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AdminVentas.setName("ventas"); // NOI18N

        AdminTaller.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        AdminTaller.setForeground(new java.awt.Color(255, 255, 255));
        AdminTaller.setText("Acceder a TALLER");
        AdminTaller.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AdminTaller.setName("taller"); // NOI18N

        javax.swing.GroupLayout MenuADMINLayout = new javax.swing.GroupLayout(MenuADMIN);
        MenuADMIN.setLayout(MenuADMINLayout);
        MenuADMINLayout.setHorizontalGroup(
            MenuADMINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuADMINLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuADMINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AdminEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AdminInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AdminFacturas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AdminNominas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AdminVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AdminTaller, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE))
                .addContainerGap())
        );
        MenuADMINLayout.setVerticalGroup(
            MenuADMINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuADMINLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AdminInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AdminFacturas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AdminNominas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AdminEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AdminVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AdminTaller, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(306, Short.MAX_VALUE))
        );

        MenuCLIENTE.setBackground(new java.awt.Color(51, 51, 51));

        ClienteInicio.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        ClienteInicio.setForeground(new java.awt.Color(255, 255, 255));
        ClienteInicio.setText("Inicio");
        ClienteInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ClienteInicio.setName("inicio"); // NOI18N

        ClienteAreaPersonal.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        ClienteAreaPersonal.setForeground(new java.awt.Color(255, 255, 255));
        ClienteAreaPersonal.setText("Área personal");
        ClienteAreaPersonal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ClienteAreaPersonal.setName("areacliente"); // NOI18N

        ClienteReservas.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        ClienteReservas.setForeground(new java.awt.Color(255, 255, 255));
        ClienteReservas.setText("Reservas");
        ClienteReservas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        ClienteFacturas.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        ClienteFacturas.setForeground(new java.awt.Color(255, 255, 255));
        ClienteFacturas.setText("Facturas");
        ClienteFacturas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout MenuCLIENTELayout = new javax.swing.GroupLayout(MenuCLIENTE);
        MenuCLIENTE.setLayout(MenuCLIENTELayout);
        MenuCLIENTELayout.setHorizontalGroup(
            MenuCLIENTELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuCLIENTELayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuCLIENTELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ClienteReservas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ClienteInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ClienteAreaPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                    .addComponent(ClienteFacturas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        MenuCLIENTELayout.setVerticalGroup(
            MenuCLIENTELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuCLIENTELayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ClienteInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ClienteAreaPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ClienteFacturas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ClienteReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(419, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelMenuLayout = new javax.swing.GroupLayout(PanelMenu);
        PanelMenu.setLayout(PanelMenuLayout);
        PanelMenuLayout.setHorizontalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MenuCLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MenuVENTAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MenuTALLER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MenuADMIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PanelMenuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {MenuADMIN, MenuCLIENTE, MenuTALLER, MenuVENTAS});

        PanelMenuLayout.setVerticalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addComponent(MenuHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuCLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMenuLayout.createSequentialGroup()
                    .addGap(0, 77, Short.MAX_VALUE)
                    .addComponent(MenuVENTAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMenuLayout.createSequentialGroup()
                    .addGap(0, 78, Short.MAX_VALUE)
                    .addComponent(MenuTALLER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMenuLayout.createSequentialGroup()
                    .addGap(0, 78, Short.MAX_VALUE)
                    .addComponent(MenuADMIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        PanelMenuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {MenuADMIN, MenuCLIENTE, MenuTALLER, MenuVENTAS});

        PanelBoard.setBackground(new java.awt.Color(242, 242, 242));
        PanelBoard.setForeground(new java.awt.Color(0, 0, 0));

        Board_Facturas.setBackground(new java.awt.Color(242, 242, 242));
        Board_Facturas.setForeground(new java.awt.Color(0, 0, 0));
        Board_Facturas.setName("facturas"); // NOI18N
        Board_Facturas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title_Facturas.setFont(new java.awt.Font("SansSerif", 3, 24)); // NOI18N
        Title_Facturas.setForeground(new java.awt.Color(0, 0, 0));
        Title_Facturas.setText("Facturas");
        Board_Facturas.add(Title_Facturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Facturas_Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Concepto", "Coste", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Facturas_Scroll.setViewportView(Facturas_Tabla);

        Board_Facturas.add(Facturas_Scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 740, 640));

        Facturas_Buscar.setText("Buscar");
        Facturas_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Facturas_BuscarActionPerformed(evt);
            }
        });
        Board_Facturas.add(Facturas_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 50, 200, -1));

        Facturas_Anadir.setText("Añadir");
        Facturas_Anadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Facturas_AnadirActionPerformed(evt);
            }
        });
        Board_Facturas.add(Facturas_Anadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 90, 200, -1));

        Facturas_Modificar.setText("Modificar");
        Facturas_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Facturas_ModificarActionPerformed(evt);
            }
        });
        Board_Facturas.add(Facturas_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 130, 200, -1));

        Facturas_Eliminar.setText("Eliminar");
        Facturas_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Facturas_EliminarActionPerformed(evt);
            }
        });
        Board_Facturas.add(Facturas_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 170, 200, -1));

        Board_Motores.setBackground(new java.awt.Color(242, 242, 242));
        Board_Motores.setForeground(new java.awt.Color(0, 0, 0));
        Board_Motores.setName("motores"); // NOI18N
        Board_Motores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelTitle_Motores.setFont(LabelTitle_Inicio.getFont());
        LabelTitle_Motores.setForeground(new java.awt.Color(0, 0, 0));
        LabelTitle_Motores.setText("Motores");
        Board_Motores.add(LabelTitle_Motores, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Board_Vehiculos.setBackground(new java.awt.Color(242, 242, 242));
        Board_Vehiculos.setForeground(new java.awt.Color(0, 0, 0));
        Board_Vehiculos.setName("vehiculos"); // NOI18N
        Board_Vehiculos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelTitle_Vehiculos.setFont(LabelTitle_Inicio.getFont());
        LabelTitle_Vehiculos.setForeground(new java.awt.Color(0, 0, 0));
        LabelTitle_Vehiculos.setText("Vehiculos");
        Board_Vehiculos.add(LabelTitle_Vehiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Board_Inicio.setBackground(new java.awt.Color(242, 242, 242));
        Board_Inicio.setForeground(new java.awt.Color(0, 0, 0));
        Board_Inicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_SesionNIF.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        Label_SesionNIF.setForeground(new java.awt.Color(0, 0, 0));
        Label_SesionNIF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_SesionNIF.setText("Sesión iniciada con: <NIF>");
        Board_Inicio.add(Label_SesionNIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 985, 60));

        LabelTitle_Inicio.setFont(new java.awt.Font("SansSerif", 3, 24)); // NOI18N
        LabelTitle_Inicio.setForeground(new java.awt.Color(0, 0, 0));
        LabelTitle_Inicio.setText("Inicio");
        Board_Inicio.add(LabelTitle_Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Board_Reservas.setBackground(new java.awt.Color(242, 242, 242));
        Board_Reservas.setForeground(new java.awt.Color(0, 0, 0));
        Board_Reservas.setName("reservas"); // NOI18N
        Board_Reservas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelTitle_Reservas.setFont(LabelTitle_Inicio.getFont());
        LabelTitle_Reservas.setForeground(new java.awt.Color(0, 0, 0));
        LabelTitle_Reservas.setText("Reservas");
        Board_Reservas.add(LabelTitle_Reservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Board_Empleados.setBackground(new java.awt.Color(242, 242, 242));
        Board_Empleados.setForeground(new java.awt.Color(0, 0, 0));
        Board_Empleados.setName("empleados"); // NOI18N
        Board_Empleados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelTitle_Empleados.setFont(LabelTitle_Inicio.getFont());
        LabelTitle_Empleados.setForeground(new java.awt.Color(0, 0, 0));
        LabelTitle_Empleados.setText("Empleados");
        Board_Empleados.add(LabelTitle_Empleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Board_Nominas.setBackground(new java.awt.Color(242, 242, 242));
        Board_Nominas.setForeground(new java.awt.Color(0, 0, 0));
        Board_Nominas.setName("nominas"); // NOI18N
        Board_Nominas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelTitle_Nominas.setFont(LabelTitle_Inicio.getFont());
        LabelTitle_Nominas.setForeground(new java.awt.Color(0, 0, 0));
        LabelTitle_Nominas.setText("Nominas");
        Board_Nominas.add(LabelTitle_Nominas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Board_AreaCliente.setBackground(new java.awt.Color(242, 242, 242));
        Board_AreaCliente.setForeground(new java.awt.Color(0, 0, 0));
        Board_AreaCliente.setName("areacliente"); // NOI18N
        Board_AreaCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelTitle_AreaCliente.setFont(LabelTitle_Inicio.getFont());
        LabelTitle_AreaCliente.setForeground(new java.awt.Color(0, 0, 0));
        LabelTitle_AreaCliente.setText("Área personal");
        Board_AreaCliente.add(LabelTitle_AreaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Board_Clientes.setBackground(new java.awt.Color(242, 242, 242));
        Board_Clientes.setForeground(new java.awt.Color(0, 0, 0));
        Board_Clientes.setName("facturas"); // NOI18N
        Board_Clientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title_Clientes.setFont(new java.awt.Font("SansSerif", 3, 24)); // NOI18N
        Title_Clientes.setForeground(new java.awt.Color(0, 0, 0));
        Title_Clientes.setText("Clientes");
        Board_Clientes.add(Title_Clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Cliente_Tabla.setModel(new javax.swing.table.DefaultTableModel(
            Cliente.devolverTodosClienteBBDD(),
            new String [] {
                "NIF", "Nombre", "Apellidos", "Telefono", "Domicilio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Clientes_Scroll.setViewportView(Cliente_Tabla);

        Board_Clientes.add(Clientes_Scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 740, 640));

        Clientes_Buscar.setText("Buscar");
        Clientes_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clientes_BuscarActionPerformed(evt);
            }
        });
        Board_Clientes.add(Clientes_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 50, 200, -1));

        Clientes_Anadir.setText("Añadir");
        Clientes_Anadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clientes_AnadirActionPerformed(evt);
            }
        });
        Board_Clientes.add(Clientes_Anadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 90, 200, -1));

        Clientes_Modificar.setText("Modificar");
        Clientes_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clientes_ModificarActionPerformed(evt);
            }
        });
        Board_Clientes.add(Clientes_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 130, 200, -1));

        Clientes_Eliminar.setText("Eliminar");
        Clientes_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clientes_EliminarActionPerformed(evt);
            }
        });
        Board_Clientes.add(Clientes_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 170, 200, -1));

        javax.swing.GroupLayout PanelBoardLayout = new javax.swing.GroupLayout(PanelBoard);
        PanelBoard.setLayout(PanelBoardLayout);
        PanelBoardLayout.setHorizontalGroup(
            PanelBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 985, Short.MAX_VALUE)
            .addGroup(PanelBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Board_Facturas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Board_Motores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Board_Vehiculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Board_Inicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Board_Reservas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Board_Empleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Board_Nominas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Board_AreaCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Board_Clientes, javax.swing.GroupLayout.DEFAULT_SIZE, 985, Short.MAX_VALUE))
        );
        PanelBoardLayout.setVerticalGroup(
            PanelBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 708, Short.MAX_VALUE)
            .addGroup(PanelBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Board_Facturas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Board_Motores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Board_Vehiculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Board_Inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Board_Reservas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Board_Empleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Board_Nominas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Board_AreaCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Board_Clientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout VentanaCompletaLayout = new javax.swing.GroupLayout(VentanaCompleta);
        VentanaCompleta.setLayout(VentanaCompletaLayout);
        VentanaCompletaLayout.setHorizontalGroup(
            VentanaCompletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaCompletaLayout.createSequentialGroup()
                .addComponent(PanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        VentanaCompletaLayout.setVerticalGroup(
            VentanaCompletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentanaCompletaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(VentanaCompleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(VentanaCompleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Facturas_AnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Facturas_AnadirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Facturas_AnadirActionPerformed

    private void Facturas_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Facturas_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Facturas_BuscarActionPerformed

    private void Facturas_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Facturas_EliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Facturas_EliminarActionPerformed

    private void Facturas_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Facturas_ModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Facturas_ModificarActionPerformed

    private void Clientes_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clientes_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Clientes_BuscarActionPerformed

    private void Clientes_AnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clientes_AnadirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Clientes_AnadirActionPerformed

    private void Clientes_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clientes_ModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Clientes_ModificarActionPerformed

    private void Clientes_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clientes_EliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Clientes_EliminarActionPerformed

    /**
     * Hace reaccionar las labels de los menús
     */
    private void addActionToMenuLabels() {
        Component[] menus = PanelMenu.getComponents();
        for (Component menu : menus) {
            System.out.println();
            JPanel contenedor = (JPanel) menu;
            Component[] components = contenedor.getComponents();
            if (menu.getName() != "Header") {
                for (Component component : components) {
                    JLabel label = (JLabel) component;

                    label.addMouseListener(new MouseListener() {
                        @Override
                        public void mouseClicked(MouseEvent e) {
                            switch (label.getName()) {
                                case "inicio":
                                    showPanel(Board_Inicio);
                                    break;
                                case "clientes":
                                    showPanel(Board_Clientes);
                                    break;
                                case "facturas":
                                    showPanel(Board_Facturas);
                                    break;
                                case "motores":
                                    showPanel(Board_Motores);
                                    break;
                                case "vehiculos":
                                    showPanel(Board_Vehiculos);
                                    break;
                                case "reservas":
                                    showPanel(Board_Reservas);
                                    break;
                                case "empleados":
                                    showPanel(Board_Empleados);
                                    break;
                                case "nominas":
                                    showPanel(Board_Nominas);
                                    break;
                                case "areacliente":
                                    showPanel(Board_AreaCliente);
                                    break;
                                case "admin":
                                    showMenu(MenuADMIN);
                                    break;
                                case "ventas":
                                    showMenu(MenuVENTAS);
                                    break;
                                case "taller":
                                    showMenu(MenuTALLER);
                                    break;
                                default:
                                    showPanel(Board_Inicio);
                            }
                        }

                        @Override
                        public void mousePressed(MouseEvent e) {
                            label.setForeground(new java.awt.Color(171, 171, 27));
                        }

                        @Override
                        public void mouseReleased(MouseEvent e) {
                            label.setForeground(new java.awt.Color(255, 255, 102));
                        }

                        @Override
                        public void mouseEntered(MouseEvent e) {
                            label.setForeground(new java.awt.Color(255, 255, 102));
                        }

                        @Override
                        public void mouseExited(MouseEvent e) {
                            label.setForeground(new java.awt.Color(255, 255, 255));
                        }
                    });
                }
            }
        }
    }

    /**
     * Cambiar panel de trabajo
     * @param panel Panel a mostrar
     */
    private void showPanel(JPanel panel) {
        for (Component pnl : PanelBoard.getComponents()) {
            JPanel pnl_f = (JPanel) pnl;
            pnl_f.setVisible(false);
        }
        panel.setVisible(true);
    }

    /**
     * Cambiar menu lateral
     * @param panel Menu a modificar
     */
    private void showMenu(JPanel panel) {
        for (Component menu : PanelMenu.getComponents()) {
            if (menu.getName() != "Header") {
                JPanel menu_f = (JPanel) menu;
                menu_f.setVisible(false);
            }
        }
        panel.setVisible(true);
    }

    /**
     * Iniciar dashboard
     *
     * @param user Uusario con el que se iniciará la interfaz
     */
    public void initGui(Empleado user) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            Dashboard gui = new Dashboard();

            /**
             * Iniciar dashboard
             */
            public void run() {
                gui.setVisible(true);
                gui.setLocationRelativeTo(null);
                configurePanels();
                gui.Label_SesionNIF.setText("Sesión iniciada con: " + user.getNif());
            }

            /**
             * Configuración inicial de los paneles
             */
            private void configurePanels() {
                gui.MenuVENTAS.setVisible(false);
                gui.MenuCLIENTE.setVisible(false);
                gui.MenuTALLER.setVisible(false);
                gui.MenuADMIN.setVisible(false);
                gui.TallerVENTAS.setVisible(false);
                gui.TallerADMIN.setVisible(false);
                gui.VentasTALLER.setVisible(false);
                gui.VentasADMIN.setVisible(false);
                switch (user.getPuestoTrabajo()) {
                    case "Administrativo":
                        gui.MenuADMIN.setVisible(true);
                        gui.TallerVENTAS.setVisible(true);
                        gui.TallerADMIN.setVisible(true);
                        gui.VentasTALLER.setVisible(true);
                        gui.VentasADMIN.setVisible(true);
                        break;
                    case "Taller":
                        gui.MenuTALLER.setVisible(true);
                        break;
                    case "Ventas":
                        gui.MenuVENTAS.setVisible(true);
                        break;
                    case "Cliente":
                        gui.MenuCLIENTE.setVisible(true);
                        break;
                    default:
                        System.out.println("Puesto no detectado");
                }
                gui.Board_AreaCliente.setVisible(false);
                gui.Board_Clientes.setVisible(false);
                gui.Board_Empleados.setVisible(false);
                gui.Board_Facturas.setVisible(false);
                gui.Board_Motores.setVisible(false);
                gui.Board_Nominas.setVisible(false);
                gui.Board_Reservas.setVisible(false);
                gui.Board_Vehiculos.setVisible(false);
                gui.Board_Inicio.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminEmpleados;
    private javax.swing.JLabel AdminFacturas;
    private javax.swing.JLabel AdminInicio;
    private javax.swing.JLabel AdminNominas;
    private javax.swing.JLabel AdminTaller;
    private javax.swing.JLabel AdminVentas;
    private javax.swing.JPanel Board_AreaCliente;
    private javax.swing.JPanel Board_Clientes;
    private javax.swing.JPanel Board_Empleados;
    private javax.swing.JPanel Board_Facturas;
    private javax.swing.JPanel Board_Inicio;
    private javax.swing.JPanel Board_Motores;
    private javax.swing.JPanel Board_Nominas;
    private javax.swing.JPanel Board_Reservas;
    private javax.swing.JPanel Board_Vehiculos;
    private javax.swing.JLabel ClienteAreaPersonal;
    private javax.swing.JLabel ClienteFacturas;
    private javax.swing.JLabel ClienteInicio;
    private javax.swing.JLabel ClienteReservas;
    private javax.swing.JTable Cliente_Tabla;
    private javax.swing.JButton Clientes_Anadir;
    private javax.swing.JButton Clientes_Buscar;
    private javax.swing.JButton Clientes_Eliminar;
    private javax.swing.JButton Clientes_Modificar;
    private javax.swing.JScrollPane Clientes_Scroll;
    private javax.swing.JButton Facturas_Anadir;
    private javax.swing.JButton Facturas_Buscar;
    private javax.swing.JButton Facturas_Eliminar;
    private javax.swing.JButton Facturas_Modificar;
    private javax.swing.JScrollPane Facturas_Scroll;
    private javax.swing.JTable Facturas_Tabla;
    private javax.swing.JLabel LabelTitle_AreaCliente;
    private javax.swing.JLabel LabelTitle_Empleados;
    private javax.swing.JLabel LabelTitle_Inicio;
    private javax.swing.JLabel LabelTitle_Motores;
    private javax.swing.JLabel LabelTitle_Nominas;
    private javax.swing.JLabel LabelTitle_Reservas;
    private javax.swing.JLabel LabelTitle_Vehiculos;
    private javax.swing.JLabel Label_SesionNIF;
    private javax.swing.JPanel MenuADMIN;
    private javax.swing.JPanel MenuCLIENTE;
    private javax.swing.JPanel MenuHeader;
    private javax.swing.JPanel MenuTALLER;
    private javax.swing.JPanel MenuVENTAS;
    private javax.swing.JPanel PanelBoard;
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JLabel TallerADMIN;
    private javax.swing.JLabel TallerClientes;
    private javax.swing.JLabel TallerFacturas;
    private javax.swing.JLabel TallerInicio;
    private javax.swing.JLabel TallerReservas;
    private javax.swing.JLabel TallerVENTAS;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel Title_Clientes;
    private javax.swing.JLabel Title_Facturas;
    private javax.swing.JPanel VentanaCompleta;
    private javax.swing.JLabel VentasADMIN;
    private javax.swing.JLabel VentasClientes;
    private javax.swing.JLabel VentasFacturas;
    private javax.swing.JLabel VentasInicio;
    private javax.swing.JLabel VentasMotores;
    private javax.swing.JLabel VentasTALLER;
    private javax.swing.JLabel VentasVehiculos;
    private javax.swing.JLabel icono;
    // End of variables declaration//GEN-END:variables
}
