/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eu.fp.concesionario;

/**
 *
 * @author Karina
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Gui
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelInicio = new javax.swing.JPanel();
        PanelLogin = new javax.swing.JPanel();
        LabelNIF = new javax.swing.JLabel();
        TextNIF = new javax.swing.JTextField();
        ButtonLOGIN = new javax.swing.JButton();
        TtitleInicio = new javax.swing.JLabel();
        ButtonCERRAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelInicio.setBackground(new java.awt.Color(204, 255, 255));
        PanelInicio.setForeground(new java.awt.Color(60, 63, 65));
        PanelInicio.setPreferredSize(new java.awt.Dimension(1280, 720));
        PanelInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelLogin.setBackground(new java.awt.Color(255, 255, 255));

        LabelNIF.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        LabelNIF.setForeground(new java.awt.Color(0, 0, 0));
        LabelNIF.setText("NIF");

        TextNIF.setBackground(new java.awt.Color(255, 255, 255));
        TextNIF.setFont(LabelNIF.getFont());
        TextNIF.setForeground(new java.awt.Color(51, 51, 51));
        TextNIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNIFActionPerformed(evt);
            }
        });

        ButtonLOGIN.setBackground(new java.awt.Color(255, 255, 255));
        ButtonLOGIN.setFont(LabelNIF.getFont());
        ButtonLOGIN.setForeground(new java.awt.Color(0, 0, 0));
        ButtonLOGIN.setText("Log in");
        ButtonLOGIN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonLOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLOGINActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLoginLayout = new javax.swing.GroupLayout(PanelLogin);
        PanelLogin.setLayout(PanelLoginLayout);
        PanelLoginLayout.setHorizontalGroup(
            PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLoginLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(LabelNIF))
            .addGroup(PanelLoginLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(TextNIF, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(PanelLoginLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(ButtonLOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelLoginLayout.setVerticalGroup(
            PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLoginLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(LabelNIF)
                .addGap(4, 4, 4)
                .addComponent(TextNIF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(ButtonLOGIN))
        );

        PanelInicio.add(PanelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 360, -1));

        TtitleInicio.setBackground(new java.awt.Color(0, 0, 0));
        TtitleInicio.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        TtitleInicio.setForeground(new java.awt.Color(0, 0, 0));
        TtitleInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TtitleInicio.setText("Inicio de sesión");
        PanelInicio.add(TtitleInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        ButtonCERRAR.setBackground(new java.awt.Color(255, 255, 255));
        ButtonCERRAR.setForeground(new java.awt.Color(0, 0, 0));
        ButtonCERRAR.setText("Cerrar");
        ButtonCERRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCERRARActionPerformed(evt);
            }
        });
        PanelInicio.add(ButtonCERRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 660, -1, -1));

        getContentPane().add(PanelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonLOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLOGINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonLOGINActionPerformed

    private void ButtonCERRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCERRARActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ButtonCERRARActionPerformed

    private void TextNIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNIFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNIFActionPerformed

    public static void main(String[] args) {
        initGui();
    }
    
    public static void initGui() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login gui = new Login();
                gui.setVisible(true);
                gui.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCERRAR;
    private javax.swing.JButton ButtonLOGIN;
    private javax.swing.JLabel LabelNIF;
    private javax.swing.JPanel PanelInicio;
    private javax.swing.JPanel PanelLogin;
    private javax.swing.JTextField TextNIF;
    private javax.swing.JLabel TtitleInicio;
    // End of variables declaration//GEN-END:variables
}
